name: Auto Update when upstream changes
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: NPM install and update assets
        run: npm ci && npm run update-assets

      - name: Check for changes
        id: diff
        run: |
          if [[ `git status --porcelain` ]]; then
            echo ::set-output name=has_changes::true
          else
            echo ::set-output name=has_changes::false
          fi

      - name: Commit updated files
        if: steps.diff.outputs.has_changes == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          message: '[auto] update assets'

      - name: NPM Version
        if: steps.diff.outputs.has_changes == 'true'
        run: npm version patch

      - name: Push changes
        if: steps.diff.outputs.has_changes == 'true'
        run: git push

      - name: Build and Publish
        if: steps.diff.outputs.has_changes == 'true'
        run: npm run build && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: get-npm-version
        if: steps.diff.outputs.has_changes == 'true'
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Release
        if: steps.diff.outputs.has_changes == 'true'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '${{ steps.package-version.outputs.current-version}}'
          body: Automatic Updates
